# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}